name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: "Tests (PHP ${{ matrix.php }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.3
            symfony-version: 7.2.*
            composer-flags: '--prefer-stable --ignore-platform-req=php+'
            stability: stable
          - php: 8.3
            symfony-version: 7.3.*
            composer-flags: '--prefer-stable'
          - php: 8.3
            symfony-version: 7.4.*
            composer-flags: '--prefer-stable'
          - php: 8.4
            symfony-version: 7.2.*
            composer-flags: '--prefer-stable'
          - php: 8.4
            symfony-version: 7.3.*
            composer-flags: '--prefer-stable'
          - php: 8.4
            symfony-version: 7.4.*
            composer-flags: '--prefer-stable'
          - php: 8.4
            symfony-version: 8.0.*
            composer-flags: '--prefer-stable'
          - php: 8.5
            symfony-version: 7.3.*
            composer-flags: '--prefer-stable'
          - php: 8.5
            symfony-version: 7.4.*
            composer-flags: '--prefer-stable'
          - php: 8.5
            symfony-version: 8.0.*
            composer-flags: '--prefer-stable'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
        run: composer update ${{ matrix.composer-flags }} --no-interaction --no-progress --optimize-autoloader

      - name: Install PDFtk
        run: sudo apt install -y pdftk

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
